server:
  port: 10010
spring:
  application:
    name: api-gateway
  redis:
    host: 192.168.15.128
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/
    registry-fetch-interval-seconds: 5   #拉取服务的配置
zuul:
  prefix: /api
  ignored-services:
    - ly-registry
    - ly-gateway
  routes:
    item-service: /item/** # 将商品微服务映射到/item/**
    upload-service: /upload/** # 将文件上传微服务映射到/upload/**
    search-service: /search/**
    user-service: /user/**
    auth-service: /auth/**
    cart-service: /cart/**
    order-service:
      path: /order/**
      serviceId: order-service
      strip-prefix: false
  sensitive-headers:
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 # 熔断超时时长：6000ms
ribbon:
  ConnectTimeout: 500 # ribbon链接超时时长
  ReadTimeout: 2000 # ribbon读取超时时长
  MaxAutoRetries: 0  # 当前服务重试次数
  MaxAutoRetriesNextServer: 1 # 切换服务重试次数
  OkToRetryOnAllOperations: false # 是否对所有的请求方式都重试，只对get请求重试
ly:                    #跨域
  cors:
    allowedOrigins:    #允许跨域的域名
      - http://manage.leyou.com
      - http://www.leyou.com
    allowedCredentials: true   #是否允许使用cookie
    allowedHeaders:
      - "*"
    allowedMethods:
      - GET
      - POST
      - DELETE
      - PUT
      - OPTIONS
      - HEAD
    maxAge: 360000
    filterPath: "/**"
  jwt:
    pubKeyPath: D:/IntelliJ IDEA WorkSpace/ssh/id_rsa.pub # C:/develop/ssh/id_rsa.pub # 公钥地址
    user:
      cookieName: LY_TOKEN # cookie名称
    app:
      id: 7
      secret: ${spring.application.name}
      headerName: privilege_token
  filter:
    allowPaths:
      - /api/auth/login
      - /api/auth/verify
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item