server:
  port: 8083
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: heima-elastic
      cluster-nodes: 192.168.15.128:9300
  rabbitmq:
    host: 192.168.15.128
    username: leyou
    password: 1143454547zw
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

